---
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
