---
name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-main
        ruby: ["3.0", "3.1", "3.2", "3.3", "head"]
        include:
          - ruby: "head"
            experimental: true
          - gemfile: "gemfiles/Gemfile-rails-main"
            experimental: true
        exclude:
          - os: "windows-latest"
            ruby: "3.0"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !!matrix.experimental }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }} with ${{matrix.gemfile}}
    steps:
      - uses: actions/checkout@v3

      - name: Remove Gemfile.lock
        if: matrix.os == 'windows-latest' && matrix.ruby == '3.1'
        run: rm Gemfile.lock

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 6

      - name: Check if documentation is up to date
        run: bundle exec rake ruby_lsp:check_docs

      - name: Typecheck
        if: matrix.os != 'windows-latest'
        run: bundle exec srb tc

      - name: Lint Ruby files
        run: bin/rubocop

      - name: Run tests
        run: bin/rails db:setup && bin/rails db:migrate && bin/rails test
